// ─── CONFIG OBJECTS FOR EACH GROUP ───────────────────────────────────

export const desktopPaperConfig = {
  // ─── Layout & Spacing ───────────────────────────────────
  width: {
    type: "numberOrPercent",
    label: "Width",
    min: 400,
    max: 1000,
    category: "layout",
    description: "Width of the paper container",
  },
  gapTop: {
    type: "number",
    label: "Gap Top",
    min: 0,
    max: 1000,
    category: "layout",
    description: "Space above the paper",
  },
  paddingTop: {
    type: "number",
    label: "Padding Top",
    min: 0,
    max: 250,
    category: "layout",
    description: "Inner spacing at top",
  },
  paddingLeft: {
    type: "number",
    label: "Padding Left",
    min: 0,
    max: 250,
    category: "layout",
    description: "Inner spacing on left",
  },
  paddingRight: {
    type: "number",
    label: "Padding Right",
    min: 0,
    max: 250,
    category: "layout",
    description: "Inner spacing on right",
  },
  paddingBottom: {
    type: "number",
    label: "Padding Bottom",
    min: 0,
    max: 250,
    category: "layout",
    description: "Inner spacing at bottom",
  },
  marginBottom: {
    type: "number",
    label: "Margin Bottom",
    min: 0,
    max: 1000,
    category: "layout",
    description: "Space below paragraphs",
  },
  scale: {
    type: "number",
    label: "Global Scale",
    min: 0.5,
    max: 2,
    step: 0.1,
    category: "layout",
    description: "Overall zoom level of the paper",
  },

  // ─── Typography ───────────────────────────────────
  font: {
    type: "font",
    label: "Font Family",
    category: "typography",
    description: "Main font for body text",
  },
  fontWeight: {
    type: "select",
    label: "Font Weight",
    category: "typography",
    description: "Thickness of the font",
    options: [
      "100",
      "200",
      "300",
      "400",
      "500",
      "600",
      "700",
      "800",
      "900",
      "normal",
      "bold",
    ],
  },
  fontColor: {
    type: "color",
    label: "Font Color",
    category: "typography",
    description: "Color of body text",
  },
  fontSize: {
    type: "number",
    label: "Font Size",
    min: 8,
    max: 72,
    category: "typography",
    description: "Size of body text",
  },
  caretColor: {
    type: "color",
    label: "Caret Color",
    category: "typography",
    description: "Color of the blinking cursor",
  },
  lineHeight: {
    type: "number",
    label: "Line Height",
    min: 8,
    max: 72,
    category: "typography",
    description: "Spacing between lines",
  },
  mentionColor: {
    type: "color",
    label: "Mention Color",
    category: "typography",
    description: "Color of @mentions",
  },

  // ─── Heading Styles ───────────────────────────────────
  h1FontSize: {
    type: "number",
    label: "Title Font Size",
    min: 8,
    max: 72,
    category: "headings",
    description: "H1 heading size",
  },
  h1LineHeight: {
    type: "number",
    label: "Title Line Height",
    min: 8,
    max: 72,
    category: "headings",
    description: "H1 line spacing",
  },
  h1MarginBottom: {
    type: "number",
    label: "Title Margin Bottom",
    min: 0,
    max: 1000,
    category: "headings",
    description: "Space below H1",
  },
  h2FontSize: {
    type: "number",
    label: "Heading 1 Font Size",
    min: 8,
    max: 72,
    category: "headings",
    description: "H2 heading size",
  },
  h2LineHeight: {
    type: "number",
    label: "Heading 1 Line Height",
    min: 8,
    max: 72,
    category: "headings",
    description: "H2 line spacing",
  },
  h2MarginBottom: {
    type: "number",
    label: "Heading 1 Margin Bottom",
    min: 0,
    max: 1000,
    category: "headings",
    description: "Space below H2",
  },
  h3FontSize: {
    type: "number",
    label: "Heading 2 Font Size",
    min: 8,
    max: 72,
    category: "headings",
    description: "H3 heading size",
  },
  h3LineHeight: {
    type: "number",
    label: "Heading 2 Line Height",
    min: 8,
    max: 72,
    category: "headings",
    description: "H3 line spacing",
  },
  h3MarginBottom: {
    type: "number",
    label: "Heading 2 Margin Bottom",
    min: 0,
    max: 1000,
    category: "headings",
    description: "Space below H3",
  },
  h4FontSize: {
    type: "number",
    label: "Heading 3 Font Size",
    min: 8,
    max: 72,
    category: "headings",
    description: "H4 heading size",
  },
  h4LineHeight: {
    type: "number",
    label: "Heading 3 Line Height",
    min: 8,
    max: 72,
    category: "headings",
    description: "H4 line spacing",
  },
  h4MarginBottom: {
    type: "number",
    label: "Heading 3 Margin Bottom",
    min: 0,
    max: 1000,
    category: "headings",
    description: "Space below H4",
  },
  h5FontSize: {
    type: "number",
    label: "Heading 4 Font Size",
    min: 8,
    max: 72,
    category: "headings",
    description: "H5 heading size",
  },
  h5LineHeight: {
    type: "number",
    label: "Heading 4 Line Height",
    min: 8,
    max: 72,
    category: "headings",
    description: "H5 line spacing",
  },
  h5MarginBottom: {
    type: "number",
    label: "Heading 4 Margin Bottom",
    min: 0,
    max: 1000,
    category: "headings",
    description: "Space below H5",
  },

  // ─── Background & Colors ───────────────────────────────────
  backgroundColor: {
    type: "color",
    label: "Background Color",
    category: "background",
    description: "Color behind the paper",
  },
  backgroundColorOpacity: {
    type: "number",
    label: "Background Opacity %",
    min: 0,
    max: 100,
    category: "background",
    description: "Opacity of the background color",
  },
  backgroundImage: {
    type: "image",
    label: "Background Image",
    category: "background",
    description: "Image behind the paper",
  },
  backgroundVideo: {
    type: "video",
    label: "Background Video",
    category: "background",
    description: "Video behind the paper",
  },
  backgroundVideoPlaybackSpeed: {
    type: "number",
    label: "Video Speed",
    min: 0.1,
    max: 5,
    category: "background",
    description: "Playback speed of background video",
  },
  paperColor: {
    type: "color",
    label: "Paper Color",
    category: "background",
    description: "Color of the paper surface",
  },
  paperColorOpacity: {
    type: "number",
    label: "Paper Opacity %",
    min: 0,
    max: 100,
    category: "background",
    description: "Opacity of the paper color",
  },
  paperBlur: {
    type: "number",
    label: "Paper Blur",
    min: 0,
    max: 100,
    category: "background",
    description: "Frosted glass blur amount",
  },

  // ─── Borders & Decorations ───────────────────────────────────
  paperBorderWidth: {
    type: "fourSidedValue",
    label: "Paper Border Width",
    category: "borders",
    description: "Thickness of paper border",
  },
  paperBorderColor: {
    type: "color",
    label: "Paper Border Color",
    category: "borders",
    description: "Color of paper border",
  },
  roundRadius: {
    type: "number",
    label: "Round Radius",
    min: 0,
    max: 50,
    category: "borders",
    description: "Corner roundness",
  },
  paperShadow: {
    type: "number",
    label: "Paper Shadow",
    min: 0,
    max: 100,
    category: "borders",
    description: "Shadow blur radius (px)",
    advanced: true,
  },
  paperShadowColor: {
    type: "color",
    label: "Paper Shadow Color",
    category: "borders",
    description: "Color of paper shadow",
  },
  borderImageTopLeft: {
    type: "image",
    label: "Top Left Corner",
    category: "borders",
    advanced: true,
  },
  borderImageTop: {
    type: "image",
    label: "Top Border",
    category: "borders",
    advanced: true,
  },
  borderImageTopRight: {
    type: "image",
    label: "Top Right Corner",
    category: "borders",
    advanced: true,
  },
  borderImageRight: {
    type: "image",
    label: "Right Border",
    category: "borders",
    advanced: true,
  },
  borderImageBottomRight: {
    type: "image",
    label: "Bottom Right Corner",
    category: "borders",
    advanced: true,
  },
  borderImageBottom: {
    type: "image",
    label: "Bottom Border",
    category: "borders",
    advanced: true,
  },
  borderImageBottomLeft: {
    type: "image",
    label: "Bottom Left Corner",
    category: "borders",
    advanced: true,
  },
  borderImageLeft: {
    type: "image",
    label: "Left Border",
    category: "borders",
    advanced: true,
  },
  borderImageWidth: {
    type: "fourSidedValue",
    label: "Border Image Width",
    category: "borders",
    description: "Thickness of border frame",
    advanced: true,
  },
  borderImageOutset: {
    type: "fourSidedValue",
    label: "Border Image Outset",
    category: "borders",
    description: "Distance from edge",
    advanced: true,
  },
  borderImageRepeat: {
    type: "select",
    label: "Border Image Repeat",
    category: "borders",
    description: "How border repeats",
    options: ["stretch", "repeat", "round", "space"],
    advanced: true,
  },
  borderImageKeepBottomFixed: {
    type: "boolean",
    label: "Keep Bottom Fixed",
    category: "borders",
    description: "Pin the bottom border to the viewport bottom",
    advanced: true,
  },
  backgroundRepeat: {
    type: "select",
    label: "Background Repeat",
    category: "background",
    description: "How background repeats",
    options: ["repeat", "no-repeat", "repeat-x", "repeat-y", "round", "space"],
  },
  backgroundPosition: {
    type: "text",
    label: "Background Position",
    category: "background",
    description: "Position of background image",
  },
  backgroundSize: {
    type: "select",
    label: "Background Size",
    category: "background",
    description: "Size of background image",
    options: ["auto", "cover", "contain", "100% 100%"],
  },

  // ─── Content Styling ───────────────────────────────────
  listPaddingLeft: {
    type: "number",
    label: "List Padding Left",
    min: 0,
    max: 250,
    category: "content",
    description: "Indentation of lists",
  },
  listMarginTop: {
    type: "number",
    label: "List Margin Top",
    min: 0,
    max: 250,
    category: "content",
    description: "Space above lists",
  },
  listMarginBottom: {
    type: "number",
    label: "List Margin Bottom",
    min: 0,
    max: 250,
    category: "content",
    description: "Space below lists",
  },
  hrMarginTop: {
    type: "number",
    label: "HR Margin Top",
    min: 0,
    max: 1000,
    category: "content",
    description: "Space above horizontal rule",
  },
  hrMarginBottom: {
    type: "number",
    label: "HR Margin Bottom",
    min: 0,
    max: 1000,
    category: "content",
    description: "Space below horizontal rule",
  },
  hrBorderColor: {
    type: "color",
    label: "HR Border Color",
    category: "content",
    description: "Color of horizontal rule",
  },
  blockquoteBorderWidth: {
    type: "number",
    label: "Blockquote Border Width",
    min: 0,
    max: 100,
    category: "content",
    description: "Thickness of blockquote border",
  },
  blockquotePadding: {
    type: "number",
    label: "Blockquote Padding",
    min: 0,
    max: 250,
    category: "content",
    description: "Inner spacing of blockquote",
  },
  blockquoteBorderColor: {
    type: "color",
    label: "Blockquote Border Color",
    category: "content",
    description: "Color of blockquote border",
  },
  spellingErrorColor: {
    type: "color",
    label: "Spelling Error Color",
    category: "content",
    description: "Underline color for spelling errors",
  },
  spellingWarningColor: {
    type: "color",
    label: "Spelling Warning Color",
    category: "content",
    description: "Underline color for grammar warnings",
  },
};

export const desktopToolbarConfig = {
  // ─── Toolbar Layout ───────────────────────────────────
  toolbarHeight: {
    type: "number",
    label: "Toolbar Height",
    min: 0,
    max: 500,
    category: "layout",
    description: "Height of toolbar container",
  },
  toolbarButtonHeight: {
    type: "number",
    label: "Toolbar Button Height",
    min: 0,
    max: 200,
    category: "layout",
    description: "Height of toolbar buttons",
  },
  toolbarButtonWidth: {
    type: "number",
    label: "Toolbar Button Width",
    min: 0,
    max: 200,
    category: "layout",
    description: "Width of toolbar buttons",
  },
  textFormatButtonWidth: {
    type: "number",
    label: "Text Format Button Width",
    min: 0,
    max: 500,
    category: "layout",
    description: "Width of text format buttons",
  },
  toolbarGapTop: {
    type: "number",
    label: "Toolbar Gap Top",
    min: 0,
    max: 500,
    category: "layout",
    description: "Space above toolbar",
  },
  toolbarFontSize: {
    type: "number",
    label: "Toolbar Font Size",
    min: 8,
    max: 72,
    category: "layout",
    description: "Font size in toolbar",
  },
  marginTop: {
    type: "number",
    label: "Margin Top",
    min: 0,
    max: 500,
    category: "layout",
    description: "Top margin",
  },
  marginBottom: {
    type: "number",
    label: "Margin Bottom",
    min: 0,
    max: 500,
    category: "layout",
    description: "Bottom margin",
  },
  marginLeft: {
    type: "number",
    label: "Margin Left",
    min: 0,
    max: 500,
    category: "layout",
    description: "Left margin",
  },
  marginRight: {
    type: "number",
    label: "Margin Right",
    min: 0,
    max: 500,
    category: "layout",
    description: "Right margin",
  },
  buttonHeight: {
    type: "number",
    label: "Button Height",
    min: 0,
    max: 500,
    category: "layout",
    description: "Height of buttons",
  },
  buttonWidth: {
    type: "number",
    label: "Button Width",
    min: 0,
    max: 500,
    category: "layout",
    description: "Width of buttons",
  },
  buttonRadius: {
    type: "number",
    label: "Button Radius",
    min: 0,
    max: 50,
    category: "layout",
    description: "Corner roundness of buttons",
  },
  buttonGap: {
    type: "number",
    label: "Button Gap",
    min: 0,
    max: 500,
    category: "layout",
    description: "Space between buttons",
  },

  // ─── Toolbar Colors ───────────────────────────────────
  backgroundColor: {
    type: "color",
    label: "Background Color",
    category: "colors",
    description: "Toolbar background color",
  },
  backgroundColorOpacity: {
    type: "percent",
    label: "Background Opacity %",
    min: 0,
    max: 100,
    category: "colors",
    description: "Opacity of the background color",
  },
  toolbarBlur: {
    type: "number",
    label: "Toolbar Blur",
    min: 0,
    max: 100,
    category: "colors",
    description: "Frosted glass blur amount",
  },
  borderColor: {
    type: "color",
    label: "Border Color",
    category: "colors",
    description: "Toolbar border color",
  },
  dividerColor: {
    type: "color",
    label: "Divider Color",
    category: "colors",
    description: "Color of divider lines",
  },
  fontColor: {
    type: "color",
    label: "Font Color",
    category: "colors",
    description: "Toolbar text color",
  },
  iconColor: {
    type: "color",
    label: "Icon Color",
    category: "colors",
    description: "Toolbar icon color",
  },
  buttonColor: {
    type: "color",
    label: "Button Color",
    category: "colors",
    description: "Button background color",
  },
  buttonBackgroundOpacity: {
    type: "percent",
    label: "Button Opacity %",
    min: 0,
    max: 100,
    category: "colors",
    description: "Opacity of the button background",
  },
  buttonBackgroundBlur: {
    type: "number",
    label: "Button Blur",
    min: 0,
    max: 100,
    category: "colors",
    description: "Frosted glass blur for buttons",
  },
  hoverColor: {
    type: "color",
    label: "Hover Color",
    category: "colors",
    description: "Button hover color",
  },
  hoverColorOpacity: {
    type: "percent",
    label: "Hover Opacity %",
    min: 0,
    max: 100,
    category: "colors",
    description: "Opacity of the hover color",
  },
  toolbarShadow: {
    type: "number",
    label: "Toolbar Shadow",
    min: 0,
    max: 100,
    category: "colors",
    description: "Shadow blur radius (px) for the utility toolbar",
  },
  toolbarShadowColor: {
    type: "color",
    label: "Toolbar Shadow Color",
    category: "colors",
    description: "Color of the utility toolbar shadow",
  },
  pressedColor: {
    type: "color",
    label: "Pressed Color",
    category: "colors",
    description: "Button pressed color",
  },
  scrollbarThumbColor: {
    type: "color",
    label: "Scroll Thumb Color",
    category: "colors",
    description: "Scroll thumb color",
  },
};

export const mobilePaperConfig = { ...desktopPaperConfig };
export const mobileToolbarConfig = { ...desktopToolbarConfig };

// Helper function to get fields by category
export const getFieldsByCategory = (config) => {
  const categories = {};
  Object.entries(config).forEach(([key, fieldConfig]) => {
    const category = fieldConfig.category || "other";
    if (!categories[category]) {
      categories[category] = {};
    }
    categories[category][key] = fieldConfig;
  });
  return categories;
};

// Category display names
export const categoryNames = {
  layout: "Layout & Spacing",
  typography: "Typography",
  headings: "Heading Styles",
  background: "Background & Colors",
  borders: "Borders & Decorations",
  content: "Content Styling",
  colors: "Colors",
  other: "Other Settings",
};
