// Separate default preferences for desktop
const TiptapDesktopDefaultPreferences = {
  paperPreferences: {
    width: "880px",
    gapTop: 32,
    paddingTop: 80, // Updated from marginTop
    paddingLeft: 96, // Updated from marginLeft
    paddingRight: 96, // Updated from marginRight
    paddingBottom: 1120, // Updated from marginBottom
    fontColor: "#FFFFFF",
    caretColor: "currentColor",
    fontWeight: "normal",
    fontSize: 20,
    lineHeight: 28,
    scale: 1,
    marginBottom: 0,
    backgroundColor: "#121212",
    backgroundColorOpacity: 100,
    backgroundImage: "",
    backgroundVideo: "",
    backgroundVideoPlaybackSpeed: 1,
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    backgroundSize: "cover",

    paperBorderWidth: "1 1 0 1  ",
    paperBorderColor: "#525252",
    paperColor: "#171717",
    paperColorOpacity: 100,
    paperBlur: 0,
    roundRadius: 8,
    paperShadow: 0,
    paperShadowColor: "#000000AA",

    h1FontSize: 40,
    h1LineHeight: 56,
    h1MarginBottom: 28,

    h2FontSize: 30,
    h2LineHeight: 42,
    h2MarginBottom: 21,

    h3FontSize: 26,
    h3LineHeight: 36.4,
    h3MarginBottom: 18.2,

    h4FontSize: 24,
    h4LineHeight: 33.6,
    h4MarginBottom: 15.4,

    h5FontSize: 22,
    h5LineHeight: 30.8,
    h5MarginBottom: 12.65,

    listPaddingLeft: 16,
    listMarginTop: 4,
    listMarginBottom: 20,
    hrMarginTop: 32,
    hrMarginBottom: 32,
    hrBorderColor: "#525252",

    blockquoteBorderWidth: 3.2,
    blockquotePadding: 32,
    blockquoteBorderColor: "#525252",
    borderImageTopLeft: "",
    borderImageTop: "",
    borderImageTopRight: "",
    borderImageRight: "",
    borderImageBottomRight: "",
    borderImageBottom: "",
    borderImageBottomLeft: "",
    borderImageLeft: "",
    borderImageWidth: "",
    borderImageOutset: "",
    borderImageRepeat: "repeat",
    mentionColor: "#a78bfa",
    spellingErrorColor: "#f87171",
    spellingWarningColor: "#60a5fa",
    borderImageKeepBottomFixed: false,
  },
  toolbarPreferences: {
    toolbarHeight: 35,
    toolbarButtonHeight: 36.8,
    toolbarButtonWidth: 36.8,
    toolbarBorderWidth: 1,
    textFormatButtonWidth: 192,
    toolbarGapTop: 8,
    toolbarFontSize: 20,
    marginTop: 4,
    marginBottom: 4,
    marginLeft: 4,
    marginRight: 4,
    buttonHeight: 28.8,
    buttonWidth: 33.6,
    buttonRadius: 8,
    buttonGap: 4,
    backgroundColor: "#171717",
    backgroundColorOpacity: 100,
    toolbarBlur: 0,
    buttonColor: "#171717",
    borderColor: "#262626",
    dividerColor: "#262626",
    iconColor: "#a3a3a3",
    fontColor: "#a3a3a3",
    hoverColor: "#121212",
    pressedColor: "#080808",
    scrollbarThumbColor: "#676767",
    buttonBackgroundOpacity: 100,
    buttonBackgroundBlur: 0,
    hoverColorOpacity: 100,
    toolbarShadow: 0,
    toolbarShadowColor: "#000000AA",
  },
};

// Mobile preferences updated with padding
const TiptapMobileDefaultPreferences = {
  paperPreferences: {
    width: `100%`,
    gapTop: 0,
    paddingTop: 19.2, // Updated from marginTop
    paddingLeft: 19.2, // Updated from marginLeft
    paddingRight: 19.2, // Updated from marginRight
    paddingBottom: 192, // Updated from marginBottom
    font: "serif",
    fontWeight: "normal",
    fontColor: "#FFFFFF",
    fontSize: 17.6,
    lineHeight: 24,
    scale: 1,
    marginBottom: 0,
    caretColor: "currentColor",
    backgroundColor: "#171717",
    backgroundColorOpacity: 100,
    backgroundImage: "",
    backgroundVideo: "",
    backgroundVideoPlaybackSpeed: 1,
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    backgroundSize: "cover",
    paperBorderWidth: 0,
    paperColor: "#171717",
    paperColorOpacity: 100,
    paperBlur: 0,
    paperBorderColor: "#525252",
    roundRadius: 0,
    paperShadow: 0,
    paperShadowColor: "#000",

    h1FontSize: 35.2,
    h1LineHeight: 48,
    h1MarginBottom: 24,

    h2FontSize: 26.4,
    h2LineHeight: 36,
    h2MarginBottom: 18,

    h3FontSize: 22.88,
    h3LineHeight: 31.2,
    h3MarginBottom: 15.6,

    h4FontSize: 21.12,
    h4LineHeight: 28.8,
    h4MarginBottom: 13.2,

    h5FontSize: 19.36,
    h5LineHeight: 26.4,
    h5MarginBottom: 10.8,

    listPaddingLeft: 16,
    listMarginTop: 20,
    listMarginBottom: 20,
    hrMarginTop: 32,
    hrMarginBottom: 32,
    hrBorderColor: "white",

    blockquoteBorderWidth: 3.2,
    blockquotePadding: 32,
    blockquoteBorderColor: "#262626",
    borderImageTopLeft: "",
    borderImageTop: "",
    borderImageTopRight: "",
    borderImageRight: "",
    borderImageBottomRight: "",
    borderImageBottom: "",
    borderImageBottomLeft: "",
    borderImageLeft: "",
    borderImageWidth: "",
    borderImageOutset: "",
    borderImageRepeat: "repeat",
    mentionColor: "#a78bfa",
    spellingErrorColor: "#f87171",
    spellingWarningColor: "#60a5fa",
    borderImageKeepBottomFixed: false,
  },
  toolbarPreferences: {
    toolbarHeight: 2.8,
    toolbarButtonHeight: 2.3,
    toolbarButtonWidth: 3,
    toolbarFontSize: 1.6,
    marginTop: 0.25,
    marginBottom: 0.25,
    marginLeft: 0.25,
    marginRight: 0.25,
    buttonHeight: 2.3,
    buttonWidth: 3,
    buttonRadius: 0.6,
    buttonGap: 0.3,
    backgroundColor: "#171717",
    backgroundColorOpacity: 100,
    toolbarBlur: 0,
    buttonColor: "#171717",
    borderColor: "#232323",
    dividerColor: "#232323",
    iconColor: "#a3a3a3",
    fontColor: "#a3a3a3",
    textFormatButtonWidth: 10,
    hoverColor: "#121212",
    pressedColor: "#080808",
    scrollbarThumbColor: "#121212",
    buttonBackgroundOpacity: 100,
    buttonBackgroundBlur: 0,
    hoverColorOpacity: 100,
    toolbarShadow: 0,
    toolbarShadowColor: "#000000AA",
  },
};

export const TipTapEditorDefaultPreferences = {
  desktopDefaultPreferences: TiptapDesktopDefaultPreferences,
  mobileDefaultPreferences: TiptapMobileDefaultPreferences,
};
