// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export async function saveAccessToken(token) {
    return await invoke("save_access_token", { token });
}

export async function loadAccessToken() {
    return await invoke("load_access_token");
}

export async function greet(name) {
    return await invoke("greet", { name });
}

export async function testCommand() {
    return await invoke("test_command");
}

export async function saveCode(code) {
    return await invoke("save_code", { code });
}

export async function loadCode() {
    return await invoke("load_code");
}
